# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8155f9fbaa4adde6741dad7416ae7f098e234c6f92f0f6a6d8d0d5aaf8987d77bece9e7fabee664595740b07a7d7dd40e7c62af2bb8733bbe4bb7b238bda1683

test:
  secret_key_base: 6f920af6cab77c717f3419d302124bf06ca2715601d0712e2ab4f53221760f7bf7a6f5848a4d7019c5daea0bced7ab7be848d7c1f3e842e5c4b2a7eb4824b36e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
